[package]
name = "group_robber"
version = "0.1.0"
authors = ["PatriotRossii <rorkh@internet.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1"
serde = { version = "1", features = ["derive"] }
reqwest = { version = "0", features = ["json"] }

[dependencies.rusqlite]
version = "0.25.1"
features = ["bundled"]
