[package]
name = "cute_fox"
version = "0.1.0"
authors = ["PatriotRossii <patriotrossii2019@mail.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1"
serde = { version = "1", features = ["derive"] }
reqwest = { version = "0", features = ["json"] }
tokio = { version = "1", features = ["rt", "macros", "rt-multi-thread", "time"] }

[dependencies.rusqlite]
version = "0.25.1"
features = ["bundled"]

[[bin]]
name = "user_from_page"
path = "tests/user_from_page.rs"

[[bin]]
name = "get_members_ids"
path = "tests/get_members_ids.rs"

[[bin]]
name = "get_members"
path = "tests/get_members.rs"